// Map sound files to an object with `uri` property
export const sounds: Record<string, any> = {
  e2: require('@/assets/sounds/notes/e2.mp3'),
  f2: require('@/assets/sounds/notes/f2.mp3'),
  g2: require('@/assets/sounds/notes/g2.mp3'),
  a2: require('@/assets/sounds/notes/a2.mp3'),
  b2: require('@/assets/sounds/notes/b2.mp3'),
  c3: require('@/assets/sounds/notes/c3.mp3'),
  d3: require('@/assets/sounds/notes/d3.mp3'),
  e3: require('@/assets/sounds/notes/e3.mp3'),
  f3: require('@/assets/sounds/notes/f3.mp3'),
  g3: require('@/assets/sounds/notes/g3.mp3'),
  a3: require('@/assets/sounds/notes/a3.mp3'),
  b3: require('@/assets/sounds/notes/b3.mp3'),
  c4: require('@/assets/sounds/notes/c4.mp3'),
  d4: require('@/assets/sounds/notes/d4.mp3'),
  e4: require('@/assets/sounds/notes/e4.mp3'),
  f4: require('@/assets/sounds/notes/f4.mp3'),
  g4: require('@/assets/sounds/notes/g4.mp3'),
  a4: require('@/assets/sounds/notes/a4.mp3'),
  b4: require('@/assets/sounds/notes/b4.mp3'),
  c5: require('@/assets/sounds/notes/c5.mp3'),
  d5: require('@/assets/sounds/notes/d5.mp3'),
  e5: require('@/assets/sounds/notes/e5.mp3'),
  f5: require('@/assets/sounds/notes/f5.mp3'),
  g5: require('@/assets/sounds/notes/g5.mp3'),
  a5: require('@/assets/sounds/notes/a5.mp3'),

  correct: require('@/assets/sounds/correct.mp3'),
  wrong: require('@/assets/sounds/incorrect.mp3'),
  tap: require('@/assets/sounds/tap.mp3'),
  metronome: require('@/assets/sounds/metronome.wav'),
};